### PR TITLE
Add plugin documentation and examples

### PR DESCRIPTION
**Pull request by abmyii**
Docs, as mentioned in #101.

I must admit that what I wrote was a bit rambling and incoherent and will need improvement and simplifying. I don't think _I_ understand plugins properly! And as Einstein said:
> “If you can't explain it to a six year old, you don't understand it yourself.” 
(https://www.goodreads.com/quotes/19421-if-you-can-t-explain-it-to-a-six-year-old)

Haha!

I hope what I've written is workable and not totally useless, because it does seem so to me a bit unfortunately!

### CODE REVIEW

**Comment by howie6879** [comment]
Thanks for your great job

**Comment by abmyii** [comment]
Um, thanks! But don't you think it is too difficult to understand?

**Comment by abmyii** [comment]
Also, I noticed a little mistake - the last line is:
```
And you should a `developer.db` should be created.
```
But should be:
```
And `developer.db` should have been created.
```

**Comment by howie6879** [comment]
you can change at any time ~

https://docs.python-ruia.org/en/examples/spider_parent_class.html

**Comment by abmyii** [comment]
Shall I start a new PR?

**Comment by howie6879** [comment]
yep

**Pull request merged**
