### PR TITLE
Don't delay retries

### PR DESCRIPTION
**Pull request by abmyii**

### CODE REVIEW

**Comment by abmyii** [comment]
I don't believe the docs will need updating as this is the expected behaviour, correct?

**Comment by howie6879** [comment]
yeah,  one small problem, line 205, should also require a delay parameter

abmyii <notifications@github.com>于2020年1月1日 周三下午10:56写道：

**Comment by abmyii** [comment]
Done.

**Comment by abmyii** [comment]
Added a test - hopefully should pass coverage.

**Comment by abmyii** [comment]
Thanks!

**Pull request merged**
